package util
{
	// This is generated by imagebundles/build.py
	public class BundleDirs
	{
		public function BundleDirs()
		{
		}
		
		// Auto-generated by imagebundles/build.py
		public static const kobBundledDirs:Object = {

		};
	}
}